[config]
default_to_workspace = false

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.readme-root]
install_crate = { crate_name = "cargo-readme", binary = "cargo", test_arg = ["readme", "--help"] }
script = ["cargo readme -r sdk > README.md"]

[tasks.readme-children]
run_task = { name = "readme-member", fork = true }

[tasks.readme-member]
workspace = true
install_crate = { crate_name = "cargo-readme", binary = "cargo", test_arg = ["readme", "--help"] }
script = ["cargo readme > README.md"]

[tasks.readme]
dependencies = [
    "readme-root",
    "readme-children"
]