[package]
authors = ["Tim Fish"]
license = "MIT"
name = "pico-driver"
version = "0.1.0"
edition = "2018"
description = "Unofficial Rust bindings and wrappers for Pico Technology oscilloscope drivers"
keywords = ["Oscilloscope", "Streaming", "PicoScope", "Pico-Technology" ]
repository = "https://github.com/meatysolutions/pico-sdk"
readme = "README.md"

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[dependencies]
pico-common = { path = "../common" }
parking_lot = "0.11"
libloading = "0.6.2"
lazy_static = "1.4"
thiserror = "^1.0.9"
c_vec = "1.3"
log-derive = "0.3"
log = "^0.4"
libffi = { git= "https://github.com/timfish/libffi-rs.git", branch = "feat/armv7-support" }
version-compare = "0.0.10"